version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/  # DEPOIS = Sucesso
    ports:
      - "8000:8000"
    env_file:
      - ./env.dev
    depends_on:
      - db

  db:
    image: postgres:15.2-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=bookstore_dev
      - POSTGRES_PASSWORD=bookstore_dev
      - POSTGRES_DB=bookstore_dev_db

volumes:
  postgres_data: